### ISSUE TITLE
csv hat 7 Spalten

### ISSUE THREAD

**Issue by balzer82** [RobTranquillo/SDM-stadtrat_dresden_metascrape#1]
Die `allfilesmeta.csv` hat in einigen Zeilen 7 Spalten, in der Überschrift sind aber nur 6 angegeben. Einfach noch eine 7. Spalte in der Zeile 1 definieren.

**Comment by RobTranquillo** [comment]
Danke. Das ist noch ein Fehler, bei umgebrochenen Sitzungs-Titeln. Kommt im nächsten fix mit rein. Bis dahin, einfach spalte 6 und 7 mergen.

**Comment by RobTranquillo** [comment]
Sollte gefixed sein im aktuellen commit. Neuer scrapeinfo/CSV output kommt auch noch.
